// <auto-generated />
using System;
using Forum.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.App.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Forum.App.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e23ac0d5-48cf-4e0d-8e59-32ff0c1aa9d8"),
                            Content = "Amidst the ancient trees, where emerald leaves dance with the breeze, a mystical grove comes alive. Listen closely, and you'll hear the whispers of the forest spirits and the secrets hidden within the rustling leaves.",
                            Title = "Whispers of the Enchanted Grove"
                        },
                        new
                        {
                            Id = new Guid("157b4187-8b5d-4107-adb1-7ff6537eef69"),
                            Content = "Embark on a journey through the lush, green canopy of the forest. High above the forest floor, the intertwining branches create a natural tapestry, allowing you to traverse through a world where sunlight filters through a million leaves, painting the ground below in a dappled mosaic.",
                            Title = "Journey Through the Verdant Canopy"
                        },
                        new
                        {
                            Id = new Guid("1f344c4a-2aa2-4745-b8d3-29d331bd36a8"),
                            Content = "The whispering pines stand tall, their needles holding the ancient wisdom of the forest. Each gust of wind carries tales of centuries past, tales of resilience and adaptation.",
                            Title = "Eternal Wisdom of the Whispering Pines"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
